/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jhotdraw.gui;

import javax.swing.JDialog;
import org.jhotdraw.draw.PredefinedFunction;

/**
 *
 * @author Joachim
 */
public abstract class AbstractFunctionPanel extends javax.swing.JPanel {

    protected boolean notDone = true;
    protected PredefinedFunction function;
    protected JDialog dialog;
    
    /**
     * Creates new form AbstractFunctionPanel
     */
    public AbstractFunctionPanel() {
        initComponents();
    }
    
    public boolean isDone() {
        return notDone;
    }
    
    public void setDialog(JDialog dialog) {
        this.dialog = dialog;
    }
    
    public abstract void setList(AbstractFunctionPanel[] list);
    
    public PredefinedFunction getGraph() {
        return this.function;
    }
    
    public abstract AbstractFunctionPanel changeFrame();
    
    @Override
    public abstract String toString();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new org.jhotdraw.gui.AbstractFunctionPanel[] {}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(326, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(170, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<org.jhotdraw.gui.AbstractFunctionPanel> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
